name: ApiUpdaterDP
author: R7vmc
version: 3.0.0
main: ApiUpdater\Base
api:
    - 3.0.0
    - 3.0.1
    - 3.0.2
    - 3.0.3
    - 3.0.4
    - 3.0.5
    - 3.0.6
commands:
    apiupdater:
        description: "The main Command"
        permission: apiupdater.use
        usage: "§f/au help"
permission:
    apiupdater.use: { description: 'Allows to use the Main command', default: op }
